### PR TITLE
fix: error when swap file is in use

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Fixes https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/242

### CODE REVIEW

**Comment by mikesmithgh** [comment]
Hi @NeilGirdhar thank you for the PR!

I prefer not to add pass any additional arguments to `nvim` by default, and let the user decide if they would like to add those arguments.

I have some examples in the `README.md`, this is similar: https://github.com/mikesmithgh/kitty-scrollback.nvim#no-configuration

For example, you could update your `kitty.conf` alias:

```
action_alias kitty_scrollback_nvim kitten /path/to/your/install/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --nvim-args -n
```

Do you know what file in particular it is having errors with related to the swap file? I am not able to reproduce this locally. If you could provide the error and let me know if you have the nvim setting `directory` set to anything in your config?

If you don't have any setting for `directory` Neovim should default writing swap files to `~/.local/state/nvim/swap`. You could list that directory when you see the error as well.


It looks like there is a buffer local option `swapfile` that can be used to disable swapfiles for specific buffers. I think that makes sense to disable for the scrollback buffer and pastewindow. That could be a fix to the issue as well if we can reproduce the problem.

**Comment by NeilGirdhar** [comment]
Thanks for taking a look!

> I prefer not to add pass any additional arguments to nvim by default, and let the user decide if they would like to add those arguments.

Without this flag, you don't even get an error.   Your console just freezes until you hit ctrl-C.  Isn't this then something that every user of your package should do?

> Do you know what file in particular it is having errors with related to the swap file? I am not able to reproduce this locally. If you could provide the error and let me know if you have the nvim setting directory set to anything in your config?

Have you tried:
* navigating to a folder, opening nvim, and editing a file, and
* in a separate tab, navigating to the same folder and editing the scrollback buffer?

Maybe I have a setting that auto-reloads the session?  I can't seem to find such a setting though.

> It looks like there is a buffer local option swapfile that can be used to disable swapfiles for specific buffers.

Awesome, how do we set that?

Also, is there a way to tell nvim not to reopen other buffers according to the saved session?  That is to ignore the session?

**Comment by mikesmithgh** [comment]
Hey @NeilGirdhar, thanks for the info. I experimented a bit and believe this is related to a session manager plugin that you may be using. Could you share what plugin you are using for session management and the config?

I don't use a session manager, so I have never encountered this issue. I tried https://github.com/rmagatti/auto-session and do see some odd results opening kitty-scrollback.nvim in a directory that has previously been opened. Sometimes it hangs, other times I get warnings related to ignoring swap files.

I'd like to see what you are using and reproduce as well.

**Comment by NeilGirdhar** [comment]
@mikesmithgh Thanks very much for looking into this, and for providing a perfect fix!

Yes, you're exactly right.  I'm using auto-session.  It seems like you've reproduced my exact problem, and your fix worked for me.

**Comment by mikesmithgh** [comment]
> @mikesmithgh Thanks very much for looking into this, and for providing a perfect fix!
> 
> 
> 
> Yes, you're exactly right.  I'm using auto-session.  It seems like you've reproduced my exact problem, and your fix worked for me.

Awesome!

**Pull request closed without merging**
