### PR TITLE
feat: add support for neovim v0.9

### PR DESCRIPTION
**Pull request by jackielii**
This PR vendors `vim.system` for neovim < v0.10 to work.

Notes:

1. `vim.uv` is not available in <v0.10, however, it seems `vim.system` is only using standard libuv functions
2. I didn't touch the version check code. Please feel free to modify

Also I didn't do thorough tests as I'm only just adopting this awesome tool! Kudos!

 for #58

### CODE REVIEW

**Comment by mikesmithgh** [comment]
thanks! is this working for you locally? if so what version of Neovim are you on?

I'll circle back to this later today or sometime tomorrow. Thanks for the contribution 👍

**Comment by jackielii** [comment]
> thanks! is this working for you locally? if so what version of Neovim are you on?
> 
> I'll circle back to this later today or sometime tomorrow. Thanks for the contribution 👍

I'm on v0.9.4, yes it's working smoothly so far!

**Comment by mikesmithgh** [comment]
hey @jackielii I think this PR is looking pretty good. I modified things a bit. Could you run `KittyScrollbackCheckHealth` on your `v0.9.4` nvim version and let me know if it runs successfully? Thanks! I need test a couple more things but think this should be good in the next day or two to merge.

**Comment by jackielii** [comment]
Nice! Just tested it and everything looks good! thanks!

**Review by mikesmithgh — APPROVED** [review]
🚀 :shipit:

**Comment by mikesmithgh** [comment]
closes #58

**Pull request merged**
